---
baseURL: "https://moisesguimaraes.com/ironcodex-website/"
languageCode: "en-us"
title: "Iron Codex"
theme: "learn"

params:
  disableLandingPageButton: true
  disableMermaid: true
  disableNextPrev: true
  themeVariant: "ironcodex"

outputs:
  home:
    - HTML
    - RSS
    - JSON
